# Scalar Evaluation

## File Input

In [90]:
import numpy as np
import itertools

In [91]:
data = np.loadtxt('dtlz2_%dobj.txt' % 2)

In [161]:
def subset_sum(numbers, target, length, result, partial=[]):
    s = sum(partial)
    #print(partial)
    # check if the partial sum is equals to target
    if round(s,15) == target and len(partial) == length:
        result.append([round(x, 15) for x in partial])
    if s >= target or len(partial)> length:
        return  # if we reach the number why bother to continue
    for i in range(len(numbers)):
        n = numbers[i]
        remaining = numbers[i+1:]
        subset_sum(remaining, target, length, result, partial + [n])

In [176]:
def weight_gen(M, H):
    weight_comps = list()
    weight_comps.append(0)
    for i in range(H):
        weight_comps.append(weight_comps[-1] + 1/H)
    print(weight_comps)
    permu = list()
    if H%M == 0:
        permu.append([round(1/M,15)]*M)
    subset_sum(weight_comps, 1, M, permu)
#     for perm in permu:
#         perm.append(round(1-sum(perm),15))
    print("total:%d" % len(permu))
    return permu

In [177]:
weight_gen(2,99)

[0, 0.010101010101010102, 0.020202020202020204, 0.030303030303030304, 0.04040404040404041, 0.05050505050505051, 0.060606060606060615, 0.07070707070707072, 0.08080808080808081, 0.09090909090909091, 0.10101010101010101, 0.1111111111111111, 0.1212121212121212, 0.1313131313131313, 0.1414141414141414, 0.15151515151515152, 0.16161616161616163, 0.17171717171717174, 0.18181818181818185, 0.19191919191919196, 0.20202020202020207, 0.21212121212121218, 0.2222222222222223, 0.2323232323232324, 0.24242424242424251, 0.2525252525252526, 0.2626262626262627, 0.2727272727272728, 0.28282828282828293, 0.29292929292929304, 0.30303030303030315, 0.31313131313131326, 0.32323232323232337, 0.3333333333333335, 0.3434343434343436, 0.3535353535353537, 0.3636363636363638, 0.3737373737373739, 0.38383838383838403, 0.39393939393939414, 0.40404040404040426, 0.41414141414141437, 0.4242424242424245, 0.4343434343434346, 0.4444444444444447, 0.4545454545454548, 0.4646464646464649, 0.47474747474747503, 0.48484848484848514, 0.4

[[0.303030303030303, 0.696969696969696],
 [0.313131313131313, 0.686868686868686],
 [0.323232323232323, 0.676767676767676],
 [0.333333333333333, 0.666666666666666],
 [0.343434343434344, 0.656565656565656],
 [0.353535353535354, 0.646464646464646],
 [0.363636363636364, 0.636363636363636],
 [0.373737373737374, 0.626262626262626],
 [0.383838383838384, 0.616161616161616],
 [0.393939393939394, 0.606060606060606],
 [0.404040404040404, 0.595959595959596],
 [0.414141414141414, 0.585858585858586],
 [0.424242424242424, 0.575757575757576],
 [0.434343434343435, 0.565656565656566],
 [0.444444444444445, 0.555555555555556],
 [0.454545454545455, 0.545454545454546],
 [0.464646464646465, 0.535353535353535],
 [0.474747474747475, 0.525252525252525],
 [0.484848484848485, 0.515151515151515],
 [0.494949494949495, 0.505050505050505]]

In [141]:
def get_best_solutions(W_vecs, data):
    for vec in W_vecs:
        result = vec*m.T

In [182]:
num_object = 4
weight_raw = []
H = 7
import copy
def combine_decrease(start, result, count, num):
    i = start
    while(i >=  count ):
        result[0,(count - 1)] = i
        if(count >1):
            combine_decrease(i - 1, result, count - 1, num)
        else:
            weight_raw.append(copy.copy(result[0]))
        i = i - 1


result = np.zeros((1,num_object-1))
combine_decrease(H+num_object-1,result,num_object-1,num_object-1)
weight_raw = np.array(weight_raw)
row_weight = int(weight_raw.shape[0])
weight_cooked = np.zeros((row_weight, num_object))
weight_cooked[0:row_weight, 0:(num_object - 1)] = weight_raw
weight_cooked[0:row_weight, (num_object - 1):(num_object)] = H + num_object
tmp = np.zeros((weight_cooked.shape))
for i in range(1,num_object):
    tmp[0:row_weight,i:i+1] = np.subtract(weight_cooked[0:row_weight,i:i+1], weight_cooked[0:row_weight,i-1:i])

weight_cooked[0:row_weight,1:num_object] = tmp[0:row_weight, 1:num_object]
weight_cooked = weight_cooked - 1
weight_cooked = weight_cooked / H
print(weight_cooked)

[[ 1.          0.          0.          0.        ]
 [ 0.85714286  0.14285714  0.          0.        ]
 [ 0.71428571  0.28571429  0.          0.        ]
 [ 0.57142857  0.42857143  0.          0.        ]
 [ 0.42857143  0.57142857  0.          0.        ]
 [ 0.28571429  0.71428571  0.          0.        ]
 [ 0.14285714  0.85714286  0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.85714286  0.          0.14285714  0.        ]
 [ 0.71428571  0.14285714  0.14285714  0.        ]
 [ 0.57142857  0.28571429  0.14285714  0.        ]
 [ 0.42857143  0.42857143  0.14285714  0.        ]
 [ 0.28571429  0.57142857  0.14285714  0.        ]
 [ 0.14285714  0.71428571  0.14285714  0.        ]
 [ 0.          0.85714286  0.14285714  0.        ]
 [ 0.71428571  0.          0.28571429  0.        ]
 [ 0.57142857  0.14285714  0.28571429  0.        ]
 [ 0.42857143  0.28571429  0.28571429  0.        ]
 [ 0.28571429  0.42857143  0.28571429  0.        ]
 [ 0.14285714  0.57142857  0.28

In [99]:
a = np.array([1,1])
m = np.matrix([[1,2],[3,4],[5,6]])

In [100]:
a*m.T

matrix([[ 3,  7, 11]])

In [103]:
x= np.array([5,4,2,1,3,5])
np.argsort(x)

array([3, 2, 4, 1, 0, 5])

In [104]:
np.argsort([2]*16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [105]:
np.argsort([2]*16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [107]:
np.argsort(np.argsort([2]*17))

array([ 0, 14, 13, 12, 11, 10,  9, 15,  8,  6,  5,  4,  3,  2,  1,  7, 16])