In [1]:
import numpy as np   

In [2]:
def evaluate_Sphere(x):
    '''
    Unimodal, separable
    '''
    return sum(x**2)

def evaluate_Rastrigin(x):
    '''
    Strong multimodal, separable
    '''
    return sum(x**2-10*np.cos(2*np.pi*x)+10)

def evaluate_Rosenbrock(x):
    '''
    Weak multimodal, nonseparable
    '''
    return sum(100*(x[1:]-x[0:-1]**2)**2+(x[0:-1]-1)**2)

In [151]:
evaluate_Rosenbrock(np.array([-2.33872135,   5.47679046,  30. ]))

31.196129856073789

In [3]:
def random_init(mu,P,D, evaluate_func,minimum,maximum):
    '''
    P:list
    mu: number of the population
    minimun: min of the domain
    maximun: max of the domain
    '''
    for i in range(mu):
        vector = np.random.rand(D)*(maximum-minimum)+minimum
        value = evaluate_func(vector)
        P.append((vector,value))
    return P

In [26]:
def BLX_alpha_cross(pa,pb,alpha,minimum,maximum):
    '''
    a special crossover mechanism for continuous optimization
    '''
    A = np.minimum(pa,pb) - alpha*np.abs(pa-pb)
    B = np.maximum(pa,pb) + alpha*np.abs(pa-pb)
    choice = np.random.choice(np.array([0,1]),size=(len(pa)))
    u = A*choice+B*(1-choice)
    u = np.minimum(u,maximum)
    u = np.maximum(u,minimum)
    return u

In [70]:
pa = np.array([1,7,1,1,1])
pb = np.array([5,6,5,5,5])

BLX_alpha_cross(pa,pb,0.5,-0.5,5)

array([-0.5,  5. , -0.5,  5. ,  5. ])

In [6]:
s = np.random.choice(np.array([0,1]),size=(len(pa)))
x = [2,2,2,2,2]
y = [3,3,3,3,3]


In [199]:
def genetic_algorithm():
    D,alpha = 5,0.2
    P = list()
    n,t = 0,0
    mu = 200
    lambda_ = mu
    evaluate_func, minimum, maximum = evaluate_Rastrigin, -5.12, 5.12
    P = random_init(mu,P,D,evaluate_func ,minimum,maximum)
    #print(P)
    x_bsf = sorted(P,key=lambda x:x[1])[0]
    #x_bsf_old = x_bsf
    count_approx = 0
    percision_abs = 1e-8
    while(x_bsf[1]>1e-8):
    #while(count_approx<200):
        #print(count_approx)
        Q = list()
        updated = False
        #print(len(P))
        for i in range(lambda_):
            # Step1 Mating Selection
            r = np.arange(len(P))
            np.random.shuffle(r)
            selected = r[:2]
            #print(selected)
            # Step2: Variation operator : Order Crossover
            u = BLX_alpha_cross(P[selected[0]][0],P[selected[1]][0],alpha,minimum,maximum)
            # Step3: Variation operator2: inversion_mutation
            # Step4: Evaluate
            new_value = evaluate_func(u)
            n += 1
            Q.append((u,new_value))
            # Step5: Update bsf solution
            if x_bsf[1]-new_value>percision_abs:
                updated = True
                print(x_bsf)
                x_bsf=(u,new_value)
        # Step6: Environment Selection
        R = P + Q
        sort_result = sorted(R,key=lambda x:x[1])
        P = sort_result[:int(len(R)/2)]
        t += 1
        if updated == True:
            #print(x_bsf)
            count_approx = 0
        else:
            count_approx += 1
    return (x_bsf,t,n)
    

In [200]:
genetic_algorithm()

(array([ 1.96272524, -0.95518482, -0.19314356, -3.02314352,  1.97818911]), 25.223841375013848)
(array([ 0.89431898,  2.01528533,  0.03115263, -0.02235102,  2.12236878]), 14.640338547465863)
(array([-0.94173387, -1.94715734,  2.00894067,  1.97535431,  0.02298331]), 14.065026366600325)
(array([-1.90585906, -1.10229961,  0.86920711, -0.06334128, -0.01571994]), 13.322950299294122)
(array([-0.98031593,  0.07261368,  0.95660098,  0.89319184, -2.11505067]), 13.290932873141639)
(array([-0.05425011, -0.04071909, -0.04832044,  1.010668  , -0.9040986 ]), 4.9875918489139144)
(array([-0.01346058, -0.99898846,  0.99607015,  1.02697379, -0.07381027]), 4.2889549435187622)
(array([ 0.07532059,  0.06114098, -0.01367368,  0.97170984,  0.0229921 ]), 3.080924086594834)
(array([  2.88146952e-02,   8.66147106e-04,   6.68000682e-02,
         9.89092919e-01,   2.40527059e-02]), 2.1531814094292425)
(array([ 0.05977832,  0.01871826,  0.02632573,  1.01709952,  0.02781768]), 2.1525886818076785)
(array([-0.00877217

KeyboardInterrupt: 

### Test result

#### Sphere fcuntion

t = 526, n = 21040
```
[ -3.19151779e-05,   6.21772535e-05,   3.37272181e-05, 6.13072638e-06,   3.23365550e-05]
7.1053532629267773e-09
```

#### Rastrigin function