In [1]:
import numpy as np   

In [2]:
def evaluate_Sphere(x):
    '''
    Unimodal, separable
    '''
    return sum(x**2)

def evaluate_Rastrigin(x):
    '''
    Strong multimodal, separable
    '''
    return sum(x**2-10*np.cos(2*np.pi*x)+10)

def evaluate_Rosenbrock(x):
    '''
    Weak multimodal, nonseparable
    '''
    return sum(100*(x[1:]-x[0:-1]**2)**2+(x[0:-1]-1)**2)

In [3]:
evaluate_Rosenbrock(np.array([-2.33872135,   5.47679046,  30. ]))

31.196129856073789

In [4]:
def random_init(mu,P,D, evaluate_func,minimum,maximum):
    '''
    P:list
    mu: number of the population
    minimun: min of the domain
    maximun: max of the domain
    '''
    for i in range(mu):
        vector = np.random.rand(D)*(maximum-minimum)+minimum
        value = evaluate_func(vector)
        P.append((vector,value))
    return P

In [5]:
def BLX_alpha_cross(pa,pb,alpha,minimum,maximum):
    '''
    a special crossover mechanism for continuous optimization
    '''
    A = np.minimum(pa,pb) - alpha*np.abs(pa-pb)
    B = np.maximum(pa,pb) + alpha*np.abs(pa-pb)
    choice = np.random.choice(np.array([0,1]),size=(len(pa)))
    u = A*choice+B*(1-choice)
    u = np.minimum(u,maximum)
    u = np.maximum(u,minimum)
    return u

In [6]:
pa = np.array([1,7,1,1,1])
pb = np.array([5,6,5,5,5])

BLX_alpha_cross(pa,pb,0.5,-0.5,5)

array([ 5. ,  5. , -0.5, -0.5,  5. ])

In [7]:
s = np.random.choice(np.array([0,1]),size=(len(pa)))
x = [2,2,2,2,2]
y = [3,3,3,3,3]


In [8]:
def genetic_algorithm():
    D,alpha = 5,0.2
    P = list()
    n,t = 0,0
    mu = 200
    lambda_ = mu
    evaluate_func, minimum, maximum = evaluate_Rastrigin, -5.12, 5.12
    P = random_init(mu,P,D,evaluate_func ,minimum,maximum)
    #print(P)
    x_bsf = sorted(P,key=lambda x:x[1])[0]
    #x_bsf_old = x_bsf
    count_approx = 0
    percision_abs = 1e-8
    #while(x_bsf[1]>1e-8):
    while(count_approx<200):
        #print(count_approx)
        Q = list()
        updated = False
        #print(len(P))
        for i in range(lambda_):
            # Step1 Mating Selection
            r = np.arange(len(P))
            np.random.shuffle(r)
            selected = r[:2]
            #print(selected)
            # Step2: Variation operator : Order Crossover
            u = BLX_alpha_cross(P[selected[0]][0],P[selected[1]][0],alpha,minimum,maximum)
            # Step3: Variation operator2: inversion_mutation
            # Step4: Evaluate
            new_value = evaluate_func(u)
            n += 1
            Q.append((u,new_value))
            # Step5: Update bsf solution
            if x_bsf[1]-new_value>percision_abs:
                updated = True
                print(x_bsf)
                x_bsf=(u,new_value)
        # Step6: Environment Selection
        R = P + Q
        sort_result = sorted(R,key=lambda x:x[1])
        P = sort_result[:int(len(R)/2)]
        t += 1
        if updated == True:
            #print(x_bsf)
            count_approx = 0
        else:
            count_approx += 1
    return (x_bsf,t,n)
    

In [10]:
genetic_algorithm()

(array([-0.89189147, -4.01449567,  1.79364549, -0.00676719, -1.03852451]), 31.060980149085214)
(array([-3.01462648,  0.98266506,  1.90729614,  0.14882261, -0.84193673]), 24.774656274404911)
(array([ 0.10581548, -2.93784895,  0.12321842, -0.08943454,  0.01742131]), 15.996241408427284)
(array([-0.00436042, -0.96405661, -2.09158283,  0.85690662, -1.08908836]), 14.395539758249217)
(array([ 0.07709752, -1.04785859,  0.10140308,  0.07854081,  1.85532678]), 13.171712124223115)
(array([ 0.03726464,  1.11101002, -0.00920945, -0.9173228 , -1.05899137]), 7.8221301652753716)
(array([-0.94450024,  0.05852049,  0.96017415,  0.04635207, -0.13153232]), 7.0647734878625501)
(array([ 0.04772738,  0.09483831,  0.08632096, -0.04012111,  0.08768145]), 5.4285396839405919)
(array([-0.03313586,  0.02749849, -0.12716529,  0.97819864,  0.03471999]), 4.6974134592052934)
(array([ 0.06998616, -0.09225626, -0.03027928, -0.01134123, -0.08432827]), 4.1834344390970628)
(array([-0.03114796,  0.03197266, -0.03614573, -1.

((array([  4.02837315e-06,  -2.38621272e-07,   4.81201831e-07,
           1.77313961e-06,  -8.93673139e-07]), 4.0588972183286387e-09),
 143,
 28600)

### Test result

#### Sphere fcuntion

t = 526, n = 21040
```
[ -3.19151779e-05,   6.21772535e-05,   3.37272181e-05, 6.13072638e-06,   3.23365550e-05]
7.1053532629267773e-09
```

#### Rastrigin function